# Risk Nav Parameters

llm_risk_node:
  ros__parameters:
    gating: true
    unknown_only: true
    danger_keywords: ['door', 'corner', 'blind', 'narrow', 'obstacle']

risk_layer_node:
  ros__parameters:
    resolution: 0.1
    width: 200
    height: 200
    origin_x: -10.0
    origin_y: -10.0

cmd_vel_risk_filter:
  ros__parameters:
    risk_gain: 0.8 